repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        args: [--config=.github/linters/.python-black, --diff]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    - id: flake8
      args: [--config=.github/linters/.flake8]
      additional_dependencies: [flake8-bugbear]
-   repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
    - id: isort
      args: [--sp=.github/linters/.isort.cfg, --diff]
-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.7.3
    hooks:
    - id: pylint
      args: [--rcfile=.github/linters/.python-lint]
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.0.0
    hooks:
    - id: pydocstyle
      args: ['--convention=google']
-   repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.0
    hooks:
    - id: darglint
      args: ['-v2', '-sgoogle']
#-   repo: https://github.com/PyCQA/bandit
#    rev: 1.7.0
#    hooks:
#    - id: bandit
#-   repo: https://github.com/jendrikseipp/vulture
#    rev: 'v2.3'
#    hooks:
#    - id: vulture
