repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-toml
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--config=.github/linters/.python-black, --diff]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      args: [--config=.github/linters/.flake8]
      additional_dependencies: [flake8-bugbear]
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
      args: [--sp=.github/linters/.isort.cfg, --diff]
-   repo: https://github.com/PyCQA/pylint
    rev: v2.13.4
    hooks:
    - id: pylint
      exclude: versioneer.py|lmpy/_version.py
      args: [--rcfile=.github/linters/.python-lint]
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
    - id: pydocstyle
      args: ['--convention=google']
-   repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
    - id: darglint
      exclude: versioneer.py|lmpy/_version.py
      args: ['-v2', '-sgoogle']
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit
      args: [-c, .github/linters/.bandit]
-   repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.3'
    hooks:
    - id: vulture
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
    -   id: forbid-tabs
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
    - id: markdownlint
      args: [--config=.github/linters/.markdownlint]
