name: lmpy
channels:
  - conda-forge
dependencies:
  - gdal
  - libspatialindex
  - rtree
  - sphinx-autoapi
  - numpy
  - defusedxml
  - coverage
  - coveralls
  - pytest
  - pytest-cov
  - requests
  - matplotlib
  - pip=22.1
  - pip:
    - sphinx-rtd-theme
    - dendropy
