[build-system]
requires = ["setuptools", "wheel"]  # PEP 508 specifications.

[tool.vulture]
exclude = ["_version.py"]
paths = ["lmpy", "tests", "tools"]
ignore_names = ["__module__", "__new__"]
# make_whitelist = true
min_confidence = 80
