name: Sphinx to GitHub Pages
on:
  push:
    tags:
      - '*.*.*' # Tag events matching {major}.{minor}.{patch}{whatever}
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      #with:
      #  fetch-depth: 0
    - name: Install library dependencies
      run: |
        pip install -r requirements.txt
    - name: Install documentation dependencies
      #uses: py-actions/py-dependency-install@v2
      #with:
      #  path: "requirements-docs.txt"
      run: |
        pip install -r requirements-docs.txt
    - name: Build and Commit
      uses: sphinx-notes/pages@1.0
      with:
        documentation_path: _sphinx_config/
    - name: Push changes to GH Pages branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
