name: Sphinx to User Manual PDF
on:
  push:
    tags:
      - '*.*.*' # Tag events matching {major}.{minor}.{patch}{whatever}
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    # Create PDF documentation
    - name: Create html docs first?
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip install -r requirements-docs.txt"
        build-command: "sphinx-build -b html . _build"
        docs-folder: "_sphinx_config/"
    - name: Create documentation pdf
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended && pip install -r requirements-docs.txt"
        build-command: "make latexpdf"
        docs-folder: "_sphinx_config/"
    # Create an artifact out of the previously built pdf.
    - name: Upload Release Asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./docs/sphinx/latex/lifemapperlmpy.pdf
        tag: ${{ github.ref }}
        overwrite: true
