name: Sphinx to GitHub Pages
on:
  push:
    tags:
      - '*.*.*' # Tag events matching {major}.{minor}.{patch}{whatever}
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Install documentation dependencies
      uses: py-actions/py-dependency-install@v2
      with:
        path: "requirements-docs.txt"
    - name: Build and Commit
      uses: sphinx-notes/pages@1.0
      with:
        documentation_path: _sphinx_config/
    - name: Push changes to GH Pages branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
    # Create PDF documentation
    - name: Create documentation pdf
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
        build-command: "sphinx-build -b latex _spinx_config/ lmpy.pdf"
        docs-folder: "_sphinx_config"
    # Create an artifact out of the previously built pdf.
    - uses: actions/upload-artifact@v1
      with:
        name: Documentation
        path: lmpy.pdf
