name: Sphinx to User Manual PDF
on:
  push:
    #tags:
    #  - '*.*.*' # Tag events matching {major}.{minor}.{patch}{whatever}
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Install documentation dependencies
      uses: py-actions/py-dependency-install@v2
      with:
        path: "requirements-docs.txt"
    # Create PDF documentation
    - name: Create html docs first?
      uses: ammaraskar/sphinx-action@master
      with:
        build-command: "sphinx-build -b html . _build"
        docs-folder: "_sphinx_config/"
    - name: Create documentation pdf
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended && ls -lahtr ./_sphinx_config/ && echo $INPUT_DOCS-FOLDER"
        build-command: "make latexpdf"
        docs-folder: "_sphinx_config/"
    # Create an artifact out of the previously built pdf.
    - uses: actions/upload-artifact@v1
      with:
        name: Documentation
        path: lmpy.pdf
