on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*.*.*' # Push events to matching {major}.{minor}.{patch}{whatever}
  workflow_dispatch:

name: Check CITATION.cff

jobs:
  check-citation-cff:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-python@v4
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import datetime
            print(os.environ)
            import yaml
            citation_fn = 'CITATION.cff'
            with open(citation_fn, mode='rt') as in_file:
                citation_data = yaml.safe_load(in_file)
            expected_version = os.environ['RELEASE_VERSION']
            expected_date = datetime.datetime.now().strftime('%Y-%m-%d')
            if not all(
                [
                    citation_data['version'] == expected_version,
                    citation_data['date-released'] == expected_date
                ]
            ):
                raise ValueError(
                    'Version and date did not match expected. ({}, {}) != ({}, {})'.format(
                        citation_data['version'],
                        citation_data['date-released'],
                        expected_version,
                        expected_date
                    )
                )
      # - name: Commit results
      #   run: |
      #     git config --local user.name "$GITHUB_ACTOR"
      #     git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
      #     git add CITATION.cff
      #     git commit -m 'Update CITATION.cff' || echo "No changes to commit"
      #     git push origin || echo "No changes to commit"
