name: PyTest with Conda

on: push

jobs:
  pytest:
    name: PyTest Conda (${{ matrix.os }}, - python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      # Checkout code
      - uses: actions/checkout@v2

      # Set up Conda environment
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: lmpy-test
          auto-activate-base: false
          auto-update-conda: true
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}

      # Get info
      - name: Debugging info
        shell: bash -l {0}
        run: |
          conda info
          conda list

      # Run pytest
      - name: Test with Pytest
        shell: bash -l {0}
        run: |
          PYTHONPATH=. coverage run --source=lmpy -m pytest tests/
          #PYTHONPATH=. pytest tests/ -v --cov lmpy --cov-report term-missing

      - name: Upload coverage data to coveralls.io
        shell: bash -l {0}
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true

  coveralls_finish:
    needs: pytest
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Coveralls Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
