on:
  release:
    types: [published]
  workflow_dispatch:

name: Update CITATION.cff

jobs:
  update-citation-cff:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - uses: jannekem/run-python-script-action@v1
        env:
          MY_TAG: '3.1.4'
          MY_DATE: '2022-05-02'
        with:
          script: |
            import os
            import yaml
            citation_fn = 'CITATION.cff'
            with open(citation_fn, mode='rt') as in_file:
                citation_data = y aml.safe_load(in_file)
            citation_data['date-released'] = get_input('MY_DATE')
            citation_data['version'] = get_input('MY_TAG')
            with open(citation_fn, mode='wt') as out_file:
                yaml.dump(citation_data, out_file
      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add CITATION.cff
          git commit -m 'Update CITATION.cff' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
